Metrics/LineLength:
  Max: 91
  Exclude:
    - 'spec/dummy/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'lib/mail/notify/mailers_controller.rb'